routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Blog\PostController;

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/blog/posts/{post}', [PostController::class, 'show'])->name('blog.show');
Route::get('/blog/categories/{category}', [PostController::class, 'category'])->name('blog.category');
Route::get('/blog/tags/{tag}', [PostController::class, 'tag'])->name('blog.tag');

Auth::routes();

Route::middleware('auth')->group(function (){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('category', 'CategoryController');

    Route::resource('post', 'PostController')->middleware('auth');

    Route::resource('tag', 'TagController');

    Route::get('/trashed-posts', 'PostController@trashed')->name('trashed-posts.index');

    Route::put('/restore-post/{post}', 'PostController@restore')->name('restore-post');
});

    Route::middleware(['auth', 'admin'])->group(function (){
        Route::get('/users/profile', 'UserController@edit')->name('user.edit-profile');
        Route::put('/users/profile', 'UserController@update')->name('user.update-profile');
        Route::get('/users', 'UserController@index')->name('users.index');
        Route::post('/users/{user}/make-admin', 'UserController@makeAdmin')->name('user.make-admin');
    });

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable =['name'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\Category\CreateCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::all();
        return view('category.index', compact('categories', $categories));
    }

    public function create()
    {
        return view('category.create');
    }


    public function store(CreateCategoryRequest $request)
    {
        Category::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'New Category Added');

        return redirect( route('category.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit(Category $category)
    {
        return view('category.create', compact('category', $category));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->update([
           'name' => $request->name
        ]);

        session()->flash('success', 'Category Updated');

        return redirect(route('category.index'));
    }

    public function destroy(Category $category)
    {
        if($category->posts->count() > 0){
            session()->flash('error', 'this category can not be deleted because it is associated with some posts');

            return redirect()->back();
        }

        $category->delete();

        session()->flash('success', 'Category Deleted');

        return redirect(route('category.index'));
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        {{ isset($category) ? 'Edit Category' : 'Create Category' }}
    </div>
    <div class="card-body">
        <form action="{{ isset($category) ? route('category.update', $category->id) : route('category.store') }}" method="POST">
            @csrf
            @if(isset($category))
                @method("PUT")
            @endif
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{ isset($category) ? $category->name : '' }}">
            </div>
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <button class="btn btn-success" type="submit">{{ isset($category) ? 'Update' : 'Add Category'}}</button>
        </form>
    </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-end mb-2">
        <a href="{{ route('category.create') }}" class="btn btn-success">Add Category</a>
    </div>

    <div class="card mb-3">
        <div class="card-header">Categories</div>
        <div class="card-body">
            @if($categories->count() > 0)
                <table class="table table-hover">
                    <thead class="thead-dark">
                    <th>Name</th>
                    <th>Posts Count</th>
                    <th></th>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->posts->count() }}</td>
                            <td>
                                <a href="{{ route('category.edit', $category->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                <button type="button" onclick="handleDelete({{ $category->id }})" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                                    Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center">No Categories Yet</h3>
            @endif

            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <form action="" method="POST" id="deleteCategoryForm">
                        @csrf
                        @method('DELETE')
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Delete Category</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p class="text-center font-weight-bold">Are you sure you want to delete this Category?</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-danger">Confirm</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        function handleDelete(id){
            var form = document.getElementById('deleteCategoryForm');
            form.action = '/category/' + id;
            $('#deleteModal').modal('show');
        }
    </script>
@endsection