routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Blog\PostController;

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/blog/posts/{post}', [PostController::class, 'show'])->name('blog.show');
Route::get('/blog/categories/{category}', [PostController::class, 'category'])->name('blog.category');
Route::get('/blog/tags/{tag}', [PostController::class, 'tag'])->name('blog.tag');

Auth::routes();

Route::middleware('auth')->group(function (){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('category', 'CategoryController');

    Route::resource('post', 'PostController')->middleware('auth');

    Route::resource('tag', 'TagController');

    Route::get('/trashed-posts', 'PostController@trashed')->name('trashed-posts.index');

    Route::put('/restore-post/{post}', 'PostController@restore')->name('restore-post');
});

    Route::middleware(['auth', 'admin'])->group(function (){
        Route::get('/users/profile', 'UserController@edit')->name('user.edit-profile');
        Route::put('/users/profile', 'UserController@update')->name('user.update-profile');
        Route::get('/users', 'UserController@index')->name('users.index');
        Route::post('/users/{user}/make-admin', 'UserController@makeAdmin')->name('user.make-admin');
    });

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
  protected $fillable = ['name'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Http\Requests\Tag\CreateTagRequest;
use App\Http\Requests\Tag\UpdateTagRequest;

class TagController extends Controller
{

    public function index()
    {
        return view('tag.index')->with('tags', Tag::all());
    }

    public function create()
    {
        return view('tag.create');
    }


    public function store(CreateTagRequest $request)
    {
        Tag::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'New Tag Added');

        return redirect( route('tag.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit(Tag $tag)
    {
        return view('Tag.create')->with('tag', $tag);
    }

    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->update([
            'name' => $request->name
        ]);

        session()->flash('success', 'Tag Updated');

        return redirect(route('tag.index'));
    }

    public function destroy(Tag $tag)
    {
        if($tag->posts->count() > 0){
            session()->flash('error', 'this tag can not be deleted because it has some post associated with it');

            return redirect()->back();
        }

        $tag->delete();

        session()->flash('success', 'Tag Deleted');

        return redirect(route('tag.index'));
    }
}

resources/views/tag/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            {{ isset($tag) ? 'Edit tag' : 'Create tag' }}
        </div>
        <div class="card-body">
            <form action="{{ isset($tag) ? route('tag.update', $tag->id) : route('tag.store') }}" method="POST">
                @csrf
                @if(isset($tag))
                    @method("PUT")
                @endif
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" id="name" value="{{ isset($tag) ? $tag->name : '' }}">
                </div>
                @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <button class="btn btn-success" type="submit">{{ isset($tag) ? 'Update' : 'Add tag'}}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/tag/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-end mb-2">
        <a href="{{ route('tag.create') }}" class="btn btn-success">Add tag</a>
    </div>

    <div class="card mb-3">
        <div class="card-header">Tags</div>
        <div class="card-body">
            @if($tags->count() > 0)
                <table class="table table-hover">
                    <thead class="thead-dark">
                    <th>Name</th>
                    <th>Posts Count</th>
                    <th></th>
                    </thead>
                    <tbody>
                    @foreach($tags as $tag)
                        <tr>
                            <td>{{ $tag->name }}</td>
                            <td> {{ $tag->posts->count() }} </td>
                            <td>
                                <a href="{{ route('tag.edit', $tag->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                <button type="button" onclick="handleDelete({{ $tag->id }})" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                                    Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center">No Tags Yet</h3>
            @endif

            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <form action="" method="POST" id="deletetagForm">
                        @csrf
                        @method('DELETE')
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Delete tag</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p class="text-center font-weight-bold">Are you sure you want to delete this tag?</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-danger">Confirm</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        function handleDelete(id){
            var form = document.getElementById('deletetagForm');
            form.action = '/tag/' + id;
            $('#deleteModal').modal('show');
        }
    </script>
@endsection